name: Flutter Build APK Manual

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release